//
//  ___COMPONENT_NAME___Testing.swift
//  Spark___COMPONENT_NAME___
//
//  Created by ___USERNAME___ on ___CURRENT_DATE___.
//  Copyright © ___CURRENT_YEAR___ Adevinta. All rights reserved.
//

import Foundation

// TODO: remove this file if there is a file no generated by sourcery !

// IMPORTANT
// This file is needed because there is
// no code (without the code generated
// by sourcery) on this target.

